apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-metrics-svc"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ .Chart.Name }}"
spec:
  selector:
    app: "{{ .Chart.Name }}"
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Release.Name }}-monitor"
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s