{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-operator-sa"
  namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Release.Name }}-operator-role"
rules:
  # PreviewEnvironment CRs — full lifecycle needed by kopf
  - apiGroups: ["devops.orima.com"]
    resources: ["previewenvironments"]
    verbs: ["get", "list", "watch", "patch", "update", "delete"]
  - apiGroups: ["devops.orima.com"]
    resources: ["previewenvironments/status"]
    verbs: ["get", "patch"]
  # Deployments — patch only (no update; patch is sufficient for rolling image changes)
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "list", "watch", "patch"]
  # Services
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "get", "list", "watch"]
  # Namespaces — note: RBAC cannot restrict by name pattern, so this grants
  # create/delete on all namespaces. Enforce preview-* restriction via OPA/Gatekeeper.
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "get", "list", "watch", "delete"]
  # Events — for kubectl describe output
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  # CRD discovery (read-only)
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  # kopf leader election
  - apiGroups: ["kopf.dev"]
    resources: ["clusterkopfpeerings", "kopfpeerings"]
    verbs: ["get", "list", "watch", "patch", "update", "create"]
  # Ingresses and NetworkPolicies
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["create", "get", "list", "watch", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Release.Name }}-operator-role-binding"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ .Release.Name }}-operator-role"
subjects:
  - kind: ServiceAccount
    name: "{{ .Release.Name }}-operator-sa"
    namespace: {{ .Release.Namespace }}
{{- end }}